"""Recommendation B, cross-language side: JS encoder == Python golden.

Feeds each committed neutral scene to the real js/encoder.js (run in node) and
asserts it reproduces the golden observation generated by the Python encoder.
This is the parity guard: if the browser encoder and the trainer encoder drift,
this fails -- instead of a trained agent silently receiving a garbled grid in the
browser.

Skips when node is unavailable (the encoder still ships; only the cross-check
is skipped).
"""

import json
import shutil
import subprocess
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FIXTURE = ROOT / "tests" / "fixtures" / "encoder_golden.json"
ENCODER = ROOT / "js" / "encoder.js"

NODE_HARNESS = """
const enc = require({encoder});
const fixture = require({fixture});
const out = fixture.scenes.map(function (scene) {{
  const s = Object.assign({{}}, scene, {{ canvas: fixture.canvas }});
  return enc.encodeObservation(s);
}});
process.stdout.write(JSON.stringify(out));
"""


@unittest.skipUnless(shutil.which("node"), "node not available to run js/encoder.js")
class EncoderJsParityTest(unittest.TestCase):
    def setUp(self):
        with open(FIXTURE, encoding="utf-8") as handle:
            self.golden = json.load(handle)

    def test_js_encoder_matches_golden(self):
        script = NODE_HARNESS.format(
            encoder=json.dumps(str(ENCODER)),
            fixture=json.dumps(str(FIXTURE)),
        )
        out = subprocess.check_output(["node", "-e", script], text=True)
        js_observations = json.loads(out)
        expected = self.golden["observations"]
        self.assertEqual(len(js_observations), len(expected))
        for scene, js_obs, want in zip(self.golden["scenes"], js_observations, expected):
            self.assertEqual(len(js_obs), len(want), scene["name"])
            for i, (got, exp) in enumerate(zip(js_obs, want)):
                self.assertAlmostEqual(
                    got, exp, places=5, msg=f"{scene['name']} index {i} (JS vs Python golden)"
                )


if __name__ == "__main__":
    unittest.main()
